import { askGemini } from './ai.js';

/**
 * Creates a structured prompt and calls Gemini to generate a max 120-word session reflection.
 * @param {Object} sessionStats - Aggregated stats from the current session.
 * @returns {Promise<string>} The learning reflection generated by Gemini.
 */
export async function generateSessionReflection(sessionStats) {
    const { 
        duration_mins, 
        words_reviewed, 
        avg_latency_ms, 
        accuracy, 
        fastest_recalled_words, 
        struggle_words 
    } = sessionStats;

    const prompt = `
You are an expert AI Learning Coach. Based on the user's study session statistics today, generate a concise Learning Reflection.

Session Stats:
- Duration: ${duration_mins} minutes
- Words Reviewed: ${words_reviewed}
- Overall Accuracy: ${accuracy}%
- Average Latency: ${avg_latency_ms} ms
- Words remembered fastest: ${fastest_recalled_words.join(', ') || 'N/A'}
- Words struggled with: ${struggle_words.join(', ') || 'N/A'}

Task Requirements:
1. Output exactly 3 bullet points:
   - Today's Strengths (Điểm mạnh hôm nay)
   - Today's Weaknesses (Điểm yếu hôm nay)
   - One Improvement Suggestion (Gợi ý cải thiện)
2. Use Vietnamese.
3. Be highly concise. Maximum 120 words total.
4. Do NOT output any other text or greetings, only the bullet points.
`;

    try {
        const reflectionText = await askGemini(prompt);
        return reflectionText;
    } catch (err) {
        console.error("Gemini Session Reflection Error:", err);
        throw new Error("Không thể tạo đánh giá lúc này, vui lòng thử lại sau.");
    }
}
